### ISSUE TITLE
An option to include files with no content

### ISSUE THREAD

**Issue by asmgf** [JohnyDays/gulp-filenames#3]
Hi,

Why files with no content are ignored? Does that give any benefits?
Would be good to be able to use it with `gulp.src('**/*.*', {read: false})` as well.

Thanks.

**Comment by JohnyDays** [comment]
Makes perfect sense, i think this is the file.isNull() call that checks if it's empty. I was not aware of this effect. I'll add this when I get some free time :+1: meanwhile, if you need this fast, you could fork and remove that call, it should do what you want.

**Comment by JohnyDays** [comment]
Got around to it, fixed in 85585ad51581698c1bb70c27dda5aa9a. Thanks again!
