### ISSUE TITLE
why does it break with streams?  

### ISSUE THREAD

**Issue by kokokenada** [JohnyDays/gulp-filenames#5]
Since you're just collecting file names, what is the point of throwing an exception if it is a streaming file?

**Comment by JohnyDays** [comment]
This was just a by-product of me having never needed streams, and throwing there being the default for gulp plugins.
If you understand how they work, it'd be cool to not throw and support them, cheers :+1:

**Comment by JohnyDays** [comment]
Check out #8 by @bmacnaughton
