### ISSUE TITLE
update to readme?

### ISSUE THREAD

**Issue by kirinmurphy** [JohnyDays/gulp-filenames#9]
hey great plugin.  just what i needed.
I was gulp watching the task that uses this, and when it gets run multiple times it doesn't clear the list from the previous run (so, dupes).  had to dig in the code a bit to figure out that .forget(namespace) fixes that.  would probably be helpful for others if that was spelled out in the docs.
Thanks!

**Comment by bmacnaughton** [comment]
My latest commit addresses this. Feel free to pull and test.

**Comment by JohnyDays** [comment]
This is now in the readme thanks to @bmacnaughton. Cheers
